name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  broken-links:
    runs-on: ubuntu-latest
    steps:
      - name: Install mintlify
        run: npm i -g mintlify
      - name: Check mintlify broken links
        run: mintlify broken-links
